name: Build and Release Binaries

on:
  push:
    branches:
      - main

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      upload_url: ${{ steps.get_upload_url.outputs.upload_url }}
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v3

      - name: Get Version
        id: get_version
        run: |
          version=$(grep '^version =' Cargo.toml | cut -d '"' -f 2)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Check if release exists
        id: check_release
        run: |
          release_id=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/v${{ steps.get_version.outputs.version }}" \
            | jq -r '.id')
          if [ "$release_id" != "null" ]; then
            echo "Release already exists"
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "release_id=$release_id" >> $GITHUB_OUTPUT
          else
            echo "Release does not exist"
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        id: create_release
        if: steps.check_release.outputs.exists == 'false'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: Release v${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false

      - name: Get upload URL
        id: get_upload_url
        run: |
          if [ "${{ steps.check_release.outputs.exists }}" == "true" ]; then
            upload_url=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/releases/${{ steps.check_release.outputs.release_id }}" \
              | jq -r '.upload_url')
          else
            upload_url="${{ steps.create_release.outputs.upload_url }}"
          fi
          echo "upload_url=$upload_url" >> $GITHUB_OUTPUT

  build_and_upload:
    name: Build and Upload
    needs: create_release
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: linux-x86_64
          - os: macos-latest
            target: x86_64-apple-darwin
            name: macos-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            name: macos-arm64
    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build binaries
        run: |
          cargo build --release --target ${{ matrix.target }} --bin jikand
          cargo build --release --target ${{ matrix.target }} --bin jk

      - name: Upload Release Asset (jikand)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./target/${{ matrix.target }}/release/jikand
          asset_name: jikand-${{ matrix.name }}
          asset_content_type: application/octet-stream

      - name: Upload Release Asset (jk)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./target/${{ matrix.target }}/release/jk
          asset_name: jk-${{ matrix.name }}
          asset_content_type: application/octet-stream

      - name: Generate checksum
        run: |
          cd target/${{ matrix.target }}/release
          sha256sum jikand jk > checksum-${{ matrix.name }}.txt

      - name: Upload checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./target/${{ matrix.target }}/release/checksum-${{ matrix.name }}.txt
          asset_name: checksum-${{ matrix.name }}.txt
          asset_content_type: text/plain
